[platformio]
build_dir = C:/pio_build/testHelo

[env]
platform = espressif32
board = esp32dev
framework = arduino
build_flags =
  -DCORE_DEBUG_LEVEL=0
upload_speed = 921600
monitor_speed = 115200
monitor_eol = LF
monitor_echo = yes
monitor_encoding = utf-8

[env:conveyor_control_com3]
build_flags =
  ${env.build_flags}
  -DDEVICE_ROLE_CONVEYOR
upload_port = COM3
monitor_port = COM3
build_src_filter =
  +<*>
  -<master_main.cpp>
  -<rs485_test_master.cpp>
  -<rs485_test_slave.cpp>

[env:master_control_com9]
build_flags =
  ${env.build_flags}
  -DDEVICE_ROLE_MASTER
upload_port = COM9
upload_speed = 115200
monitor_port = COM9
build_src_filter =
  +<master_main.cpp>

[env:rs485_test_master_com9]
build_flags =
  ${env.build_flags}
upload_port = COM9
upload_speed = 115200
monitor_port = COM9
build_src_filter =
  +<rs485_test_master.cpp>

[env:rs485_test_slave_com3]
build_flags =
  ${env.build_flags}
upload_port = COM3
upload_speed = 115200
monitor_port = COM3
build_src_filter =
  +<rs485_test_slave.cpp>
